name: Test release

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get version
      run: echo "::set-env name=VERSION::$(echo $GITHUB_REF | cut -d'/' -f 3)"
    - name: Use version
      run: echo The version is $VERSION
