name: Test release

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get version
      run: | 
        VERSION="echo $GITHUB_REF | cut -d'/' -f 3"
        VERSION="${VERSION}"
        echo $VERSION
        echo "::set-env name=VERSION::$VERSION"
    - name: Use version
      run: echo The version is $VERSION
