name: Test release

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get tag name
      run: |
        TAGNAME=$(echo $GITHUB_REF | cut -d'/' -f 3)
        echo The tag name is $TAGNAME
        echo "::set-env name=TAGNAME::$TAGNAME"
    - name: Use tag name
      run: echo The version is $TAGNAME
